### ISSUE TITLE
memf: Why reinventing the wheel? Where is the difference to scanmem?

### ISSUE THREAD

**Issue by sriemer** [fst3a/cheatkit#26]
I'm the maintainer of [scanmem/GameConqueror](https://github.com/scanmem/scanmem).
Why should people use your `memf` instead of scanmem or GameConqueror?
Which unique feature does it provide?

scanmem/GameConqueror is the best memory scanner on Linux, Jolla smartphones, and Android AFAIK. There is even a port for FreeBSD.

**Comment by fst3a** [comment]
Oh well, I had no idea about scanmem/GameConqueror before I started working on cheatkit.  I created cheatkit because of personal needs.  `memf` seems to offer no advantage over scanmem/GameConqueror other than having smaller, simpler codebase and more liberal license, so far.

**Comment by fst3a** [comment]
Oh well, I had no idea about scanmem/GameConqueror before I started working on cheatkit.  I created cheatkit because of personal needs.  `memf` seems to offer no advantage over scanmem/GameConqueror other than having smaller/simplier code base and more liberal license, so far.

**Comment by sriemer** [comment]
Thanks for the explanation! Would be great to work together on Linux memory scanning and game cheating to avoid duplicate efforts.

Btw.: With [ugtrain](https://github.com/ugtrain/ugtrain) I'm also developing a Linux game trainer with dynamic memory and ASLR/PIC/PIE support. `scanmem` provides the match offsets and ugtrain just has to add the current load address of the executable to support static memory cheating with position-independent executables (PIE).

Question answered. So closing. Thanks!

**Comment by fst3a** [comment]
i will look into that, thanks for telling
